Portfolio-Responsive-Movile-Version
SaveryIV/Portfolio-Responsive pull request #2
Opened 2023-04-29 18:03 UTC by SaveryIV

In this project, I end:

   -The data Grid with the cards.
   -The About Myself, with the lists.
   -The buttons hover, pressed, and disconnected propertys.

2023-04-29 18:53 UTC, Owusu-Desmond requested changes
Hi @SaveryIV , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Nice UI design ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 18:53 UTC, Owusu-Desmond commented on style.css
> -  }
- [ ] From the project requirements, you should stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0), But the dot divider is not present in all your project card so please make sure that you fix it :pray: 
  
  | Your Design |Figma Design |
  | :---:   | :---: | 
  | ![image](https://user-images.githubusercontent.com/92303891/235319041-335ab0a2-a123-4dfc-a3b4-e870ed2a9008.png) | ![image](https://user-images.githubusercontent.com/92303891/235318851-768b5905-0cf8-4164-ba75-c6e680f19dde.png) |
  

- [ ] Also as you can see, all your project title's colors and and the company (for instance the "Canopy") color does not match the Figma design so make sure that you fix them

2023-04-29 18:53 UTC, Owusu-Desmond commented on style.css
- [ ] Please this card image it not showing so make sure that you fix it to make your work match the Figma design. :pray: 
  
  ![image](https://user-images.githubusercontent.com/92303891/235319276-8353b5dc-ab35-461e-b69f-540685eed38b.png)

2023-04-29 18:53 UTC, Owusu-Desmond commented on README.md
- [ ] Why dont you remove these comments below you have in your readme from your readme file to make it more professional :blush: 
    - "_Describe the tech stack and include only the relevant sections that apply to your project._"
    - "_Describe between 1-3 key features of the application._"

2023-04-29 19:26 UTC, SaveryIV commented
I Desmond, i dont now how change the color of text "CANOPY".
The other thing is i dont now why the image is like that, because in my browser seems right

2023-04-29 19:27 UTC, SaveryIV commented
Let me pass pls because is almost exactly the same. 
This is how seems to me
![image](https://user-images.githubusercontent.com/85071975/235320803-5652a998-9327-4c08-b8e0-ce3c358b4bdd.png)

2023-04-29 19:32 UTC, Owusu-Desmond commented
If you are sure that the image is showing your side then it can be running
problems at my side. Please fix the  requested changes left and submit for
review again

On Sat, 29 Apr 2023 at 7:26 PM, Agustin Soria ***@***.***>
wrote:

> I Desmond, i dont now how change the color of text "CANOPY".
> The other thing is i dont now why the image is like that, because in my
> browser seems right
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SaveryIV/Portfolio-Responsive/pull/2#issuecomment-1528855869>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWAHEE2FZR2TCHJ4FL2HPCTXDVTORANCNFSM6AAAAAAXQLQUAY>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-04-29 19:33 UTC, SaveryIV commented
Can show me how pls? I tried but i can't @Owusu-Desmond

2023-04-29 19:38 UTC, Owusu-Desmond commented
Hi @SaveryIV,

Please which of the suggested changes do
you not get it so that I can elaborate further

2023-04-29 19:39 UTC, SaveryIV commented
> Hi @SaveryIV,
> 
> Please which of the suggested changes do you not get so that I can elaborate further

The dots between the words

2023-04-29 19:48 UTC, SaveryIV commented
@Owusu-Desmond Okey i think i fnish now, i made the changes

2023-04-29 19:49 UTC, Trast00 reviewed
Hi @SaveryIV , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that failed linters, consider fixing the linter and making sure all of them are green, and then ask for a review. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@Trast00) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-29 19:54 UTC, SaveryIV commented
> Hi @SaveryIV ,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that failed linters, consider fixing the linter and making sure all of them are green, and then ask for a review.
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me(@Trast00) in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

Now i fixed, the linters are working well

2023-04-29 20:05 UTC, Trast00 approved these changes
# Approved 🟢
Hi @SaveryIV , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![allfather-approves-approved](https://user-images.githubusercontent.com/74411135/225065704-3948f35e-94b9-4440-a31a-29bba50b3c4d.gif)

## Highlights
- Project look awsome 🍏 🌷 
- Code is clean and well organized 🧼 💯 

## Optional suggestions

- [ ] Kindly, replace the image URL at line [194](https://github.com/SaveryIV/Portfolio-Responsive/blob/master/index.html#L164) from `/resources/work-section/masks/Snapshoot PortfolioMulti-Post2-mask.png` by  `./resources/work-section/masks/Snapshoot PortfolioMulti-Post2-mask.png`. The dot at the beginning oof the URL make sure the image always display properly. This will make your project way more prettier which will improve the user experience 📱  😄 👍 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@Trast00) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 20:45 UTC, merged

2023-06-02 11:45 UTC, Bantealem reviewed
Hi @SaveryIV, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

## Highlights
- [x] No lInters error
- [x] Correct Github flow
- [x] Descriptive PR title and  Summary
- [x] Professional README
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._